services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: askflow-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./askflow-frontend
      dockerfile: Dockerfile.frontend
    container_name: askflow-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: askflow
      POSTGRES_USER: askflow
      POSTGRES_PASSWORD: askflow_password123
    volumes:
      - postgres_data:/var/lib/postgresql/dat
    # No ports exposed to the internet â€“ backend can still reach it by name "db"
