services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: askflow-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=askflow
      - DB_USER=askflow
      - DB_PASSWORD=askflow_password123
      - DB_HOST=db

  frontend:
    build:
      context: ./askflow-frontend
      dockerfile: Dockerfile.frontend
    container_name: askflow-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: askflow
      POSTGRES_USER: askflow
      POSTGRES_PASSWORD: askflow_password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
