services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: askflow-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./askflow-frontend
      dockerfile: Dockerfile.frontend
    container_name: askflow-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
